#!/usr/bin/env node
/**
 * Generates packages/core/src/data.generated.ts from the canonical JSON.
 *
 * The JSON is the source of truth (PRD AR-6) so an adapter in another language
 * reads the same ruleset. This step exists only so the TypeScript packages can
 * import it without a JSON import assertion, which behaves differently across
 * the Workers runtime, Node ESM and every bundler in between.
 */
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const core = join(here, '..', 'packages', 'core')

const strip = (o) => {
  if (Array.isArray(o)) return o.map(strip)
  if (o && typeof o === 'object') {
    return Object.fromEntries(
      Object.entries(o).filter(([k]) => k !== '$comment').map(([k, v]) => [k, strip(v)]),
    )
  }
  return o
}

const ruleset = strip(JSON.parse(readFileSync(join(core, 'data', 'ruleset.json'), 'utf8')))
const ranges = strip(JSON.parse(readFileSync(join(core, 'data', 'ranges.json'), 'utf8')))

// Lower-case the match needles once, at build time, so `classify` does not do
// it per request. This runs on a hot path under NF-1.
for (const a of ruleset.agents) a.match = a.match.map((m) => m.toLowerCase())
const genericBotHints = ruleset.genericBotHints.match.map((m) => m.toLowerCase())

const out = `// GENERATED by scripts/generate-data.mjs — do not edit.
// Source of truth: packages/core/data/ruleset.json and packages/core/data/ranges.json

export interface RulesetAgent {
  readonly name: string
  readonly bucket: string
  readonly purpose: string
  readonly vendor: string
  readonly match: readonly string[]
}

export const RULESET = {
  version: ${JSON.stringify(ruleset.version)} as string,
  buckets: ${JSON.stringify(ruleset.buckets)} as readonly string[],
  purposes: ${JSON.stringify(ruleset.purposes)} as readonly string[],
  notAUserAgent: ${JSON.stringify(ruleset.notAUserAgent.tokens)} as readonly string[],
  agents: ${JSON.stringify(ruleset.agents, null, 2)} as readonly RulesetAgent[],
  genericBotHints: ${JSON.stringify(genericBotHints)} as readonly string[],
} as const

export const RANGES = {
  version: ${JSON.stringify(ranges.version)} as string,
  updatedAt: ${JSON.stringify(ranges.updatedAt)} as string | null,
  ranges: ${JSON.stringify(ranges.ranges, null, 2)} as Readonly<Record<string, readonly string[]>>,
} as const
`

writeFileSync(join(core, 'src', 'data.generated.ts'), out)

// The WordPress adapter is PHP and shares no code with core, so it reads the
// ruleset as data (PRD AR-6). Copied verbatim rather than retyped, and copied
// here rather than by hand so the two can never drift.
const wp = join(here, '..', 'wordpress', 'spoor-data')
mkdirSync(wp, { recursive: true })
for (const name of ['ruleset', 'ranges']) {
  copyFileSync(join(core, 'data', `${name}.json`), join(wp, `${name}.json`))
}
console.log(
  `generated data.generated.ts — ruleset ${ruleset.version}, ${ruleset.agents.length} agents, ` +
  `ranges ${ranges.version} (${Object.keys(ranges.ranges).length} buckets populated)`,
)
console.log('copied ruleset.json + ranges.json → wordpress/spoor-data/')
